writer1       = console
writer1.format = {date: HH:mm:ss.SSS} {level}: {class}.{method}()\n{message}
writer1.level = info

writer2      = rolling file
writer2.file = usage_logs/info/{date:yyyy}/{date:MM}/{pid}_{count}.log
writer2.format = {date: HH:mm:ss.SSS} {level}: {class}.{method}()\n{message}
writer2.latest = usage_logs/info/latest.log
writer2.backups  = 10
writer2.level = info

writer3      = rolling file
writer3.file = usage_logs/debug/{date:yyyy}/{date:MM}/{pid}_{count}.log
writer3.format = {date: HH:mm:ss.SSS} {level}: {class}.{method}()\n{message}
writer3.latest = usage_logs/debug/latest.log
writer3.backups  = 10
writer3.level = debug

writingthread = true